Repository ESE-Peasy/NarrateMyWay, pull requests merged in 2021-02, with the labels that each got.

#3 Initialise React Native project
  .gitignore
  app/.expo-shared/assets.json
  app/App.tsx
  app/app.json
  app/assets/fonts/SpaceMono-Regular.ttf
  app/assets/images/adaptive-icon.png
  app/assets/images/favicon.png
  app/assets/images/icon.png
  app/assets/images/splash.png
  app/babel.config.js
  app/components/EditScreenInfo.tsx
  app/components/StyledText.tsx
  app/components/Themed.tsx
  app/components/__tests__/StyledText-test.js
  app/constants/DefaultColors.ts
  app/constants/Layout.ts
  app/hooks/useCachedResources.ts
  app/hooks/useColorScheme.ts
  app/hooks/useColorScheme.web.ts
  app/navigation/BottomTabNavigator.tsx
  app/navigation/LinkingConfiguration.ts
  app/navigation/index.tsx
  app/package.json
  app/screens/NotFoundScreen.tsx
  app/screens/TabOneScreen.tsx
  app/screens/TabTwoScreen.tsx
  app/tsconfig.json
  app/types.tsx
Labels: app development

#11 Created templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#15 Update docs for linux env install
  .gitignore
  app/package.json
  docs/_site/about-us.html
  docs/_site/assets/css/just-the-docs-dark.css
  docs/_site/assets/css/just-the-docs-default.css
  docs/_site/assets/css/just-the-docs-light.css
  docs/_site/assets/images/just-the-docs.png
  docs/_site/assets/images/search.svg
  docs/_site/assets/js/just-the-docs.js
  docs/_site/assets/js/search-data.json
  docs/_site/assets/js/vendor/lunr.min.js
  docs/_site/guidance.html
  docs/_site/images/logo.svg
  docs/_site/index.html
  docs/development/installation.md
Labels: documentation

#16 Miklasr/5 screen reading and text to speech
  .github/PULL_REQUEST_TEMPLATE.md
  app/package.json
  app/screens/TabTwoScreen.tsx
  docs/code-style/accessibility.md
  docs/code-style/code-style.md
  docs/development/development.md
  docs/guidance.md
Labels: app development

#19 Initial UI
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/main.yml
  .gitignore
  app/components/BeaconInfo.tsx
  app/components/LargeButton.tsx
  app/components/Separators.tsx
  app/components/__tests__/Components-test.js
  app/components/__tests__/StyledText-test.js
  app/components/__tests__/__snapshots__/Components-test.js.snap
  app/components/styles/BeaconInfo.style.tsx
  app/components/styles/LargeButton.style.tsx
  app/components/styles/Separators.style.tsx
  app/navigation/BottomTabNavigator.tsx
  app/package-lock.json
  app/package.json
  app/screens/MainScreen.tsx
  app/screens/TabOneScreen.tsx
  app/types.tsx
Labels: app development

#21 Update logo
  docs/images/logo.svg
Labels: documentation

#27 Scanning screen
  .gitignore
  app/components/BeaconInfo.tsx
  app/components/LargeButton.tsx
  app/components/ScanningButton.tsx
  app/components/__tests__/Components-test.js
  app/components/__tests__/__snapshots__/Components-test.js.snap
  app/components/styles/ScanningButton.style.tsx
  app/constants/DefaultColors.ts
  app/constants/Header.ts
  app/ios/NarrateMyWay.xcodeproj/project.pbxproj
  app/ios/NarrateMyWay.xcodeproj/xcshareddata/xcschemes/NarrateMyWay.xcscheme
  app/ios/NarrateMyWay/Supporting/Expo.plist
  app/navigation/BottomTabNavigator.tsx
  app/navigation/LinkingConfiguration.ts
  app/navigation/index.tsx
  app/screens/MainScreen.tsx
  app/screens/NotFoundScreen.tsx
  app/screens/ScanningScreen.tsx
  app/screens/TabTwoScreen.tsx
  app/types.tsx
Labels: front-end

#20 8 location codes
  docs/NMW-Standard/Location-Encoding.md
  docs/NMW-Standard/NMW-Standard.md
  docs/index.md
Labels: documentation

#29 New sequence diagrams and documentation
  docs/about-us.md
  docs/images/NMW-Main-New-Location.pdf
  docs/images/NMW-Main.pdf
  docs/images/NMW-Setup.pdf
  docs/images/PlantUML/nmw-main-new-location.puml
  docs/images/PlantUML/nmw-main.puml
  docs/images/PlantUML/nmw-setup.puml
  docs/system/nmw-main-app.md
  docs/system/nmw-setup-app.md
  docs/system/overall-system-design.md
  docs/system/system.md
Labels: documentation
